"""empty message

Revision ID: 385d805d4680
Revises: 
Create Date: 2021-07-06 23:44:01.071358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385d805d4680'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('congacs', sa.Column('seo_description_cognac', sa.String(length=240), nullable=True))
    op.add_column('factories', sa.Column('seo_description_factory', sa.String(length=240), nullable=True))
    op.add_column('factories', sa.Column('id_country', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'factories', 'countrys', ['id_country'], ['id_country'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'factories', type_='foreignkey')
    op.drop_column('factories', 'id_country')
    op.drop_column('factories', 'seo_description_factory')
    op.drop_column('congacs', 'seo_description_cognac')
    # ### end Alembic commands ###
